import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import Header from '../Components/Header'
import Global, { FormContent, Main } from '../styles/global'
import styles from '../styles/Home.module.css'

import { useState } from 'react';
import Input from '../Components/Input'
import Button from '../Components/Button'

import firebase from '../firebaseConnection'
import Footer from '../Components/Footer'
const Home: NextPage = () => {
  const [name,setName] = useState<String>('')
  const [email,setEmail] = useState<String>('')
  async function handleSave()
  {
    await firebase.firestore().collection('user')
    .add({
      Name: name,
      Email: email
    })
    .then(() => {
      alert("Dados Cadastrados com Sucesso!")
      setName('')
      setEmail('')
    })
    .catch((err)=>{
      alert ("Falha ao salvar dados.Entre em contato com o administrador do sistema")
      console.log(err)
    })
  }
 
  return (
    <>
    <Global/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>

      

      <Main>

      <FormContent>
      <Input
        labelName="Nome Completo: "
        placeHolderInput = 'Insira o seu nome aqui'
        typeInput = 'text'
        changed = {(e)=>{setName(e.target.value)}}
        valueInput = {name}
        />

      <Input
        labelName="E-mail: "
        placeHolderInput = 'Exemplo.: abc@def.com'
        typeInput = 'text'
        changed = {(e)=>setEmail(e.target.value)}
        valueInput = {email}
        />

        <Button 
        name = "Salvar Usuário"
        clicked = {handleSave}  />
      </FormContent>
      
      </Main>

     <Footer/>
    </>
  )
}

export default Home
